use_frameworks!

target 'LPAUIKit_Example' do
  pod 'LPAUIKit', :path => '../'

  target 'LPAUIKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
